name: pizzeria_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0

  # DB
  mongo_dart: ^0.10.1

  # Functional programming
  dartz: ^0.10.1

  # Utils
  dart_jsonwebtoken: ^2.13.0
  encrypt: ^5.0.3
  # crypto: ^3.0.3
  uuid: ^4.3.3

  # Data models
  pizzeria_shared:
    path: ../pizzeria_shared

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
