name: pizzeria_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  objectid: ^3.0.0

  dio: ^5.4.2+1
  retrofit: ^4.1.0

  go_router: ^13.2.2

  intl: ^0.19.0

  sizer: ^2.0.15

  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  pizzeria_shared:
    path: ../pizzeria_shared

  cached_network_image: ^3.3.1  

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30
  flutter_staggered_grid_view: ^0.7.0
  custom_sliding_segmented_control: ^1.8.1
  shimmer: ^3.0.0
  modal_bottom_sheet: ^3.0.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
